const ADD_PAYEE = 'ADD_PAYEE';
const UPDATE_PAYEE = 'UPDATE_PAYEE';
const LIST_PAYEE = 'LIST_PAYEE';
const ADD_PERSONAL_DETAILS = 'ADD_PERSONAL_DETAILS';
const UPDATE_PERSONAL_DETAILS = 'UPDATE_PERSONAL_DETAILS';
const ADD_TRANSACTION = 'ADD_TRANSACTION';
const LIST_TRANSACTION = 'LIST_TRANSACTION';
const LOGIN = 'LOGIN';
const REGISTER = 'REGISTER';
const RESET_PASSWORD = 'RESET_PASSWORD';

export {
    ADD_PAYEE,
    UPDATE_PAYEE,
    LIST_PAYEE,
    ADD_PERSONAL_DETAILS,
    UPDATE_PERSONAL_DETAILS,
    ADD_TRANSACTION,
    LIST_TRANSACTION,
    LOGIN,
    REGISTER,
    RESET_PASSWORD
};
