export const FETCHING_PAYEE = "FETCHING_PAYEE";
export const FETCHING_PAYEE_SUCCESS = "FETCHING_PAYEE_SUCCESS";
export const FETCHING_PAYEE_FAILURE = "FETCHING_PAYEE_FAILURE";

export const FETCHING_ACCOUNT = "FETCHING_ACCOUNT";
export const FETCHING_ACCOUNT_SUCCESS = "FETCHING_ACCOUNT_SUCCESS";
export const FETCHING_ACCOUNT_FAILURE = "FETCHING_ACCOUNT_FAILURE";

export const FETCHING_ADDRESS = "FETCHING_ADDRESS";
export const FETCHING_ADDRESS_SUCCESS = "FETCHING_ADDRESS_SUCCESS";
export const FETCHING_ADDRESS_FAILURE = "FETCHING_ADDRESS_FAILURE";

export const FETCHING_TRANSACTION = "FETCHING_TRANSACTION";
export const FETCHING_TRANSACTION_SUCCESS = "FETCHING_TRANSACTION_SUCCESS";
export const FETCHING_TRANSACTION_FAILURE = "FETCHING_TRANSACTION_FAILURE";

export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER = "LOGIN_USER";


